export const sampleNotes = [
  {
    id: "notes-sample-1",
    title: "Babel & Modern JavaScript",
    body: "Babel merupakan compiler JavaScript open-source yang digunakan untuk mengubah sintaks ECMAScript 2015+ (ES6+) menjadi versi JavaScript yang kompatibel ke belakang agar dapat berjalan dengan mulus di berbagai browser lama maupun modern.",
    createdAt: "2026-09-18T14:30:00.000Z",
    archived: false,
  },
  {
    id: "notes-sample-2",
    title: "Web Components Architecture",
    body: "Teknologi standar web seperti Custom Elements, Shadow DOM, dan HTML Templates memungkinkan developer membangun elemen UI kustom yang terenkapsulasi, independen, dan reusable tanpa harus bergantung pada framework eksternal.",
    createdAt: "2026-09-18T13:15:00.000Z",
    archived: false,
  },
  {
    id: "notes-sample-3",
    title: "Prinsip Desain UI/UX Modern",
    body: "Kunci kenyamanan aplikasi produktivitas terletak pada visual hierarchy yang jelas, kontras warna yang ramah di mata, micro-animations yang halus, serta respon antarmuka yang cepat untuk memaksimalkan fokus pengguna.",
    createdAt: "2026-09-18T11:45:00.000Z",
    archived: false,
  },
  {
    id: "notes-sample-4",
    title: "Optimasi Kinerja Web Application",
    body: "Meningkatkan performa web melalui teknik code-splitting dengan Webpack, lazy loading gambar, kompresi aset statis, serta meminimalisir reflow dan repaint dengan memanfaatkan properti CSS transform.",
    createdAt: "2026-09-18T10:00:00.000Z",
    archived: false,
  },
  {
    id: "notes-sample-5",
    title: "Modularisasi Kode & Clean Architecture",
    body: "Penerapan ECMAScript Modules (ESM) membantu pemisahan tanggung jawab kode (Separation of Concerns). Kode menjadi lebih mudah dibaca, mudah diuji dengan unit testing, serta terstruktur untuk skala pengembangan besar.",
    createdAt: "2026-09-18T08:20:00.000Z",
    archived: false,
  },
  {
    id: "notes-sample-6",
    title: "Sprint Planning & Roadmap Q4",
    body: "Daftar prioritas tim: migrasi komponen ke dark mode modern, integrasi indikator loading interaktif menggunakan SweetAlert2, dan audit performa Core Web Vitals (FCP, LCP, CLS).",
    createdAt: "2026-09-17T16:00:00.000Z",
    archived: true,
  },
  {
    id: "notes-sample-7",
    title: "Setup Webpack & Development Tooling",
    body: "Konfigurasi webpack.common.js, webpack.dev.js, dan webpack.prod.js telah selesai disesuaikan untuk mendukung live reloading pada port 8003 dan optimasi bundling aset otomatis.",
    createdAt: "2026-09-17T14:30:00.000Z",
    archived: true,
  },
];
